version: '3.3'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data_monitor:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - monitor-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - SHARDEUM_RPC_URL=${SHARDEUM_RPC_URL}
      - PRIMARY_SENDER_PRIVATE_KEY=${PRIMARY_SENDER_PRIVATE_KEY}
      - PRIMARY_RECEIVER_ADDRESS=${PRIMARY_RECEIVER_ADDRESS}
      - SECONDARY_SENDER_PRIVATE_KEY=${SECONDARY_SENDER_PRIVATE_KEY}
      - SECONDARY_RECEIVER_ADDRESS=${SECONDARY_RECEIVER_ADDRESS}
      - TRANSACTION_AMOUNT=${TRANSACTION_AMOUNT}
      - MONITOR_INTERVAL=${MONITOR_INTERVAL}
      - PORT=3000
      - CORS_ORIGIN=http://34.18.31.242:3000
    restart: unless-stopped
    networks:
      - monitor-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VITE_API_URL=${VITE_API_URL:-http://34.18.31.242:3001/api}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
      - prometheus
    restart: unless-stopped
    networks:
      - monitor-network

networks:
  monitor-network:
    driver: bridge

volumes:
  prometheus_data_monitor: