global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'shardeum-monitor'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/metrics'